### ISSUE TITLE
Accessing agc->enable

### ISSUE THREAD

**Issue by BobSelf22** [fventuri/gr-sdrplay3#34]
Is agc->enable accessible from my python app? I'd like to be able to get the state of this flag.

thanks

**Comment by fventuri** [comment]
@BobSelf22
You should be able to get the status of the AGC (enabled/disabled) by using the method `get_gain_mode()` (see here: https://github.com/fventuri/gr-sdrplay3/blob/main/include/gnuradio/sdrplay3/rsp.h#L131-L136), for instance:
```
    agc = myrsp.get_gain_mode()
    print(agc)
```

Franco
