### ISSUE TITLE
tunerParams->ifType?

### ISSUE THREAD

**Issue by BobSelf22** [fventuri/gr-sdrplay3#36]
Is tunerParams->ifType accessible from my python app?

thanks

**Comment by fventuri** [comment]
No.
I just ran a quick grep in the `include` directory (https://github.com/fventuri/gr-sdrplay3/tree/main/include/gnuradio/sdrplay3), and I don't see any function returning it (or the IF bandwidth, bwType, along with the decimation, and many other internal settings).

Franco
